### ISSUE TITLE
Type Image leads to memory error

### ISSUE THREAD

**Issue by aersamkull** [pacman82/arrow-odbc-py#17] opened 2022-04-22 09:32 UTC
Hi there

I have a column of SQL Server which is of type image. SQL Server reports MaxLength = 2147483647. This results in the following error in arrow-odbc-py: 
`memory allocation of 107374182350000 bytes failed`

Somehow I cannot even catch this error. I guess you are using kind of a buffer that grows too much with such a high max length. I propose to impose a max length and throw an error that is recoverable - or really fix it by not using a fixed-sized buffer

**Comment by aersamkull** [comment] 2022-04-22 11:28
Given  #11 I think it would be best to allow the user to define an upper limit of bytes per column. If the ODBC Field Length is not meaningful (<=0) or greater then the max length specified, try using the given limit and if it exceeds the limit, throw. This way I could set 32K as an Upper Limit of a Column if I know that this should be enough. If I increase this size and want so same me some RAM I could just decrease the Batch Size

**Comment by pacman82** [comment] 2022-04-22 16:11
Hello @aersamkull ,

thanks for opening the issue. In short specifying an upper limit can make sense. I wonder if I could better understand and reproduce the error first.

> I have a column of SQL Server which is of type image

Two questions here:

* Do you mean Microsoft SQL Server? Or another kind of server
* Since IMAGE is not a standard SQL type. What is the exact declaration of the column.

I am asking about the type, since part of me is afraid that `arrow-odbc` might try to fetch the image as an UTF-8 string, since this is the catch all for all unknown types. So I would like to reproduce that first.

> `memory allocation of 107374182350000 bytes failed`
>
> Somehow I cannot even catch this error.  I guess you are using kind of a buffer that grows too much with such a high max length.

Your guess is on the spot. The buffer does not grow though. It is preallocated in one go. Giving a recoverable error feels to, me like a seperate issue in its own right. Users might specify an upper bound which is still to high. The reason you can not catch anything is that it is very likely that the underlying native Rust code in this scenario just aborts execution. We'll have to use a failable allocation than creating the buffer and forward the error. Then this should be recoverable.

> \- or really fix it by not using a fixed-sized buffer

I think that might be much harder to do then one might guess 😅 . Maybe even impossible. ODBC demands preallocated buffers, which are able to hold an entire batch. I can not grow them mid query. That being said, there are streaming interfaces for large individual values. However large indivual values are not the primary scope of this library, but bulk fetching lots of rows into columnar storage. The interface for streams would also be very different. A lot of the fancier ODBC features are also a bit of hit and miss in terms of support with different drivers. Microsoft SQL seems to work great though.

**Sugested workaround:**

One of the things you might try, to get done what you need to get done until this is fixed:

Since `buffer_size = max_field_size * batch_size`. Setting the `batch_size` to one might help avoiding the allocation error in the meantime.

Cheers, Markus

**Comment by aersamkull** [comment] 2022-04-22 18:00
Yes I mean MS SQL Server. `image` is an old deprecated type, see [MSFT Docu](https://docs.microsoft.com/en-us/sql/t-sql/data-types/ntext-text-and-image-transact-sql?view=sql-server-ver15). It's basically a varbinary(MAX) type from the last century

For me a user-defined max-size would be good enough. I've seen guys using a SQL Column to store a Json with a Base64 Encoded PDF in it but that's not me or my company ;) My use case is user-entered HTML or something the like which won't grow over 32K Characters or so

**Comment by pacman82** [comment] 2022-04-24 14:09
Hello @aersamkull ,

version `0.1.19` of `arrow-odbc` has been released. It will raise a recoverable error instead of arborting program execution in case of an allocation error for a binary or varchar column.

This of course only concludes the "bug" part of your experience. Question is: "Is your usecase enabled, too?".

I was happy to see in the tests that an `Image` column is reported to be a `LONG_VARBINARY` within the ODBC type system. For me a query like `SELECT CAST(my_image as VARBINARY(2048)) FROM MyTable` worked fine.

Does this work for you? How do you feel about that?

Cheers, Markus

**Comment by aersamkull** [comment] 2022-04-25 09:15
Hi Markus
Thanks for this very fast release! It makes my life easier as I can now skip the error parts with image/nvarchar(MAX)/varbinary(MAX). However the acutual use case is not covered yet. 

MS SQL Server has only support for in-row for up to 8000 bytes. If you need more, you have to use the MAX types. Such types exist in other RDBMS, too; the just have different names. MySql for example has a number of [`BLOB`](https://dev.mysql.com/doc/refman/8.0/en/blob.html) types which don't delivery a meaningful length, too (it's a very large number in their INFORMATION_SCHEMA.COLUMNS). For these types a configurable Max Size is needed, so that I can tell arrow-odbc-py that my fields all have at most N bytes, no matter what ODBC says. This would enable a number of use cases. Meaning ODBC would probably return 0 or something very large for the field size but you truncate it to the given number of bytes (or throw, doesn't matter). Often we use this type of fields for JSON or long User-written texts in any language and don't need more then 100K Bytes per field. If I have a decent server with 200GB RAM I can load a lot of these. 

Regards,
Adrian

**Comment by pacman82** [comment] 2022-04-26 18:22
Hello Adrian,

> Thanks for this very fast release! It makes my life easier as I can now skip the error parts with image/nvarchar(MAX)/varbinary(MAX). However the acutual use case is not covered yet.

Thank you for the feedback, this took me the better part of a Saturday, so it is nice to know you appreciate it.

Also thanks for elaborating on your usecase. Especially the hint with the rough size of 100kb has been helpful. Otherwise I might have suggested that it is out of scope, since large pictures probably shouldn't be fetched in bulk, but streamed individually.

I think specifying a maximum binary size of an element in a buffer, might be the way to go (as you suggested). However I need to see how I can check for truncation in a perfromant way. If I just forward the argument the truncation done by ODBC will be VERY silent. I would like for the default behaviour to emit an exception, but maybe that will have to wait for a second iteration.

It would also be nice if I had a way to report warnings to the user, but I've not interfaced the Python logging with Rust yet in any way.

As of now I can not make any promises then I get to this, or how long it will take me.

Regards, Markus

**Comment by aersamkull** [comment] 2022-04-27 07:06
Hello Markus
Yes you're right, large files should be fetched differently. MS SQL Server even has a streaming feature for those so you don't have to load these completely to RAM. 

Well the silence of the truncation is not nice, but I personally could live with it - I could check the size at server level. 

Just by the way: We did a lot of checks regarding performance using various approaches and this library was by far the fastest. 

For me this is not urgent and if it gets urgent I can still do a quick and dirty hack by using a fork ;) (I don't have Rust experience nor Python Interop experience...)

Regards,
Adrian

**Comment by pacman82** [comment] 2022-05-06 06:45
Hello Adrian,

`arrow-odbc 0.1.20` does support specifying upper limits for binary and text column buffers. I am leaving this issue open, still because the upstream change I made to provide fallibable allocations, seemed to have some performance issues, I've been unaware of.

See: <https://github.com/pacman82/odbc-api/issues/192>

I am still thinking about what the best behaviour for this crate should be, given that the cost for the check is high, but also that the allocation error is hard to spot for a Python user, which might not even see the panic.

**Comment by aersamkull** [comment] 2022-05-06 08:48
Great news! Thanks!
I'll test asap and give you Feedback.
About the memory error: this is much more unlikely now, I'd be fine with an unrecoverable error if it causes perf trouble

**Comment by pacman82** [comment] 2022-05-13 21:58
Hello Adrian,

Closing this issue as I assume this is now solved for you. Would still like to hear about it. You can opt out of the fallibale allocations by setting `falliable_allocations` to `False`.

Cheers, Markus

**Closed by pacman82** 2022-05-13 21:58 UTC
Labels: enhancement
